version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:REEMPLAZA_ESTO_CON_LA_TUYA
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: locations
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      API_KEY: SoyAbundancia11
    command: php artisan serve --host=0.0.0.0 --port=8000
    working_dir: /var/www/html

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: locations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
