version: '3.8'

services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: locations_db_56nf
      POSTGRES_USER: locations_db_56nf_user
      POSTGRES_PASSWORD: mHx1ivlkpo1ISAzhrA0tFAB2X0EPHymd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  artisan:
    build:
      context: .
    image: laravel-app
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    entrypoint: ["php", "artisan"]

volumes:
  pgdata:
