services:
  - type: web
    name: locations-api-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://locations-api-backend.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d24ko83e5dus73dd1fug-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: locations_db_56nf
      - key: DB_USERNAME
        value: locations_db_56nf_user
      - key: DB_PASSWORD
        sync: false
      - key: API_KEY
        sync: false
